export const START_GET_PRIME_LT_NUMBER_REQUEST = 'START_GET_PRIME_LT_NUMBER_REQUEST';
export const GET_PRIME_LT_NUMBER = 'GET_PRIME_LT_NUMBER';
export const GET_PRIME_LT_NUMBER_ERROR = 'GET_PRIME_LT_NUMBER_ERROR';
export const CLEAR_PRIME_LT_NUMBER_RESPONSE = 'CLEAR_PRIME_LT_NUMBER_RESPONSE';